name: Deploy csvcubed-models whl
on:
  workflow_call:

jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package

      - name: Publish whl to test pypi
        if: github.ref_name == 'main'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish whl to pypi
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          
      - id: is-final-release 
        if: startsWith(github.ref, 'refs/tags/v') 
        run: | 
          [[ ! "${{github.ref_name}}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ ]]
        continue-on-error: true
